### ISSUE TITLE
Suggestion on standardizing names

### ISSUE THREAD

**Issue by razcore-rad** [Beliaar/godot-yaml#2]
Hello, first off thanks, I was looking into some other options than JSON/CSV and YAML is just perfect for what I have in mind.

I'd like to propose these changes that will make the file be more friendly to be edited by hand, for content creators:

- use the same exact name for property names as godot does in the exposed scripting languages, well I say "languages" but I mean GDScript really, cause that's the "official". For example `Rect2` should use `position` instead of `pos`, `Transform2D` should use `x`, `y` & `origin` etc. I can work on a PR if you want, if not I'll just work on a fork as I think these are really important. When someone searches about Godot data types they go to the documentation, not the code, and in the documentation, there's `Rect2.position` and so on
- remove `Variant` from `!<Godot/Variant/Transform2D>`. Is there anything that isn't `Variant` apart from simple types that don't need comments?

**Comment by Beliar83** [comment]
Heya,

I am not quite sure why I choose those names, but if those you suggested are better for people you can go ahead an make these changes as a PR.

About Variant, I think when I started there were some non Variant types, but I realized that the json Parser does not serialize those, and they are difficult to serialize, if at all possible, so I left them out as well.
If godot is unlikely to add other complex object types that people want to serialize then it can be removed. Do you want to make a PR for that yourself, too? If not I will do that in the next days.

**Comment by razcore-rad** [comment]
removing `Variant` is just changing one line of string no? ya, I think I can do it :)

edit: I think you chose `pos` and other names cause that's what you saw in the godot C++ source code, but I think it's much better to use the names found in the documentation

**Comment by Beliar83** [comment]
Well, probably both when storing and parsing, but yeah, should be easy.

edit: [here](https://github.com/Beliaar/godot-yaml/blob/0cb6acaf4ca0652bd5de25120b56ccee50d7d560/src/godotconversions.cpp#L211) and [here](https://github.com/Beliaar/godot-yaml/blob/0cb6acaf4ca0652bd5de25120b56ccee50d7d560/src/godotconversions.cpp#L331) should be where the changes have to be made. Could probably change from github, but cannot test at the moment. 
I should probaly look for a unit testing framework for C++ some time.

And I think that is probably so, I mostly checked the C++ code while doing this.

**Comment by razcore-rad** [comment]
Oh ya, thanks, I figured it out :)
