### ISSUE TITLE
Treat quoted values as string

### ISSUE THREAD

**Issue by razcore-rad** [Beliaar/godot-yaml#7]
something like
```yaml
position:
  bool: true
  string: "true"
```
is parsed as `{position: {"bool": True, "string": True}}`, but it makes more sense to parse it as: `{position: {"bool": True, "string": "true"}}`

someone else implemented this in their own project like so: https://github.com/chenxiaolong/DualBootPatcher/pull/754/files

**Comment by razcore-rad** [comment]
Morning! I see you made some changes to treat quoted strings as strings, that's cool, but we need to do the same when encoding, that is, for string values to be saved with quotes cause otherwise we loose this information. Say if we encode this dictionary: `{"somekey": "5"}` and for some reason it has to be string, it will be converted to:
```yaml
somekey: 5
```
so when we read it back it's gonna be an int.

I think we can do this the smart way, that is if it's not a string that can be converted to built-in types then save without quotes, otherwise save with quote or something like that. What do you say?

**Comment by Beliar83** [comment]
Ah, right, I forgot that. I think we should save every string explicitly value with quotes, though, to ensure they will always be parsed as strings. This is more safe without that much negative effects.

**Comment by razcore-rad** [comment]
Well I'll tell you the reason why I think a "smart" option is better. First of all it's a YAML feature, to have strings without quotes that is, so if I have a manually created file and read it with this parser, do some processing, then resave, I'll loose my initial formatting.

I was looking in godot-yaml as an alternative to JSON because YAML is less verbose. And I think it can make for a decent content creation tool, for example for dialog systems. I first started off with JSON, but really JSON is cumbersome to write and maintain, doesn't allow comments etc. I looked at YAML with the idea of content-creators in mind, not programmers.

And I just think it's a good idea to have the same representation when encoding/decoding on read/write. So if I expect my YAML file to be able to be read with strings that don't include quotes (except for "special" data - `bool`, `int` etc.) then I expect the encoder to also do that.

Hope it was clear :)

**Comment by Beliar83** [comment]
Ok, I checked how pyyaml does it, and they do it as you say. I have to see how that can be done, though.

**Comment by razcore-rad** [comment]
I checked your code and I think it's pretty easy. If the `Variant` is a string it already goes to:
```cpp
case Variant::STRING: {
  String string = rhs.operator String();
  node = string.alloc_c_string();
  break;
}
```
we just need to check if `string` can be cast-ed safely to built-in types like `bool`, `float`(`double`?), `int`, and if so we tag the node: `node.Tag("!")` (I assume it's the same as decoding) or `SetTag()`.

**Comment by razcore-rad** [comment]
Started working on it on this branch: https://github.com/razcore-art/godot-yaml/tree/string-quotes, although `SetTag("!")` doesn't work. I'll check yaml-cpp documentation, we'll get it done :)

**Comment by razcore-rad** [comment]
ref. jbeder/yaml-cpp#664

**Comment by razcore-rad** [comment]
So I found this https://stackoverflow.com/questions/7017564/how-to-emit-a-string-with-quotes-using-yaml-cpp, but I'm not exactly sure how to use it. I only checked yaml-cpp briefly, but as I understand, it uses `encode` under the hood for encoding individual nodes, but how do you make the connection with the `Emitter`, that I'm not sure. In any case, I think exploring this solution is the approach we have to take.

**Comment by Beliar83** [comment]
Yeah, that looks promising,

**Comment by razcore-rad** [comment]
:) I don't think that's exactly the solution, now we get:
```yaml
str_bool: "\"true\""
str_int: "\"1\""
str_float: "\"3.4\""
```
on encoding.

**Comment by Beliar83** [comment]
I know, but that is how yaml-cpp emits it, and I am quite losing patience with it. Also they are parsed correctly that way anyway.

**Comment by razcore-rad** [comment]
Yes, I know why it does that, you're just adding quotes to the "inner values" so they're escaped by yaml-cpp because quotes are special symbols. I'll eventually do it, I just need to find some time to play with the thing a bit more.

**Comment by Beliar83** [comment]
@razcore-art  Btw, if you want to take over, it would be ok for me. I still like yaml, but my active C++ days are far in the past, and it probably shows in the code. I just started this because there was no other yaml plugin, and I prefer yaml over json.

**Comment by razcore-rad** [comment]
Sorry, I meant to answer but I completely forgot. Unfortunately I'm in pretty much the same place with C++ and I never was really that advanced with it to begin with. I tried looking at that yaml library and I didn't get that far. Even if I'd like to have full support in godot, I don't think I'm the guy for the job.
